import { Inter } from 'next/font/google'
import NextTopLoader from 'nextjs-toploader';
import './globals.css'
import ReduxProvider from './provider/ReduxProvider';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({ children }) {
  return (
    <ReduxProvider>
        <html lang="en">
          <body className={inter.className}><NextTopLoader color='var(--pink)' showSpinner={false}/>{children}</body>
        </html>
    </ReduxProvider>
  )
}
