import NextTopLoader from 'nextjs-toploader';
import './globals.css'
import ReduxProvider from './provider/ReduxProvider';
export const metadata = {
  title: 'PHOTO AI',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ReduxProvider>
        <html lang="en">
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
          <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800;900&display=swap" rel="stylesheet" />
          <body><NextTopLoader color='var(--pink)' showSpinner={false}/>{children}</body>
        </html>
    </ReduxProvider>
  )
}
